server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 18080
  adminConnectors:
    - type: http
      port: 18081

logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
  appenders:
    - type: console